### PR TITLE
Added linters

### PR DESCRIPTION
**Pull request by chepkok3**
Added the correct linters with the right format.
Added the gitignore file to the root directory.
Added  .hintrc file to the project root directory.
Added  .stylelintrc.json file to the root directory of the project.

### CODE REVIEW

**Review by Kamba56 — COMMENTED** [review]
Hi @chepkok3 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that ** has no running linters checks ** Kindly make sure that linters checks is running correctly on github

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by chepkok3** [comment]
***@***.**** I have made changes to the sylint but it still cannot run checks
on github. Is there a way I can fix this?

**Comment by Kamba56** [comment]
@chepkok3 Try correcting the file path to linters.yml

linters yml file should be in .github/workflows folder

Note: the workflows folder is inside the .github folder and contains the linters.yml file

**Comment by chepkok3** [comment]
Thanks. I did that and it worked!

**Comment by chepkok3** [comment]
***@***.****  Please review it.

**Pull request merged**
